#!/bin/sh

# do_backup database table

if [ $# -lt 3 ]; then
  echo "$0 <base rep> <database> <table> [<table> [...]]" 1>&2
  exit 1
fi

BASEDIR="$1"
schema="$2"
shift 2

for table in "$@"; do

   # Prepare
   DIR="$BASEDIR/$schema/$table"
   mkdir -p "$DIR"

   LASTFILE="$DIR/last"
   CURRENT="$DIR/current"
   /usr/bin/pg_dump -h localhost --no-owner --schema $schema --table $table | /usr/bin/bzip2 -c > "$DIR/current"

   if test -f "$LASTFILE" && /usr/bin/diff -q "$CURRENT" "$LASTFILE" > /dev/null
   then
      # Files are the same
      echo -n
   else
      # OK, keep backup (move it to the good directory)
      SQLDIR="$DIR"/$(/bin/date "+%Y/%m/%d")
      FILE="$SQLDIR"/$(/bin/date "+assessments@%H%M").sql.bz2
      /bin/mkdir -p "$SQLDIR"
      mv "$CURRENT" "$FILE"
      ln -sf "$FILE" "$DIR"/last
   fi

#mail -s "Backup done $(/bin/date "+%Y%m%d%M%H")" bpiwowar
done
