#!/bin/sh

# Prepare cache

# --- Check arguments

function usage {
	error=0
	if test "$1"; then
		echo "$1"
		error=1
	fi
	echo "prepare_cache <xml directory> <cache directory>"
	exit 0
}

if [ $# -ne 2 ]; then
	usage "Needs 2 arguments"
fi

for d in "$@"; do
	test -d "$d" || usage "$d is not a directory"
done

# --- Do it

# Others can write
umask 0020

for d in $(cd $1; find -type d); do
	if [ ! -d "$2/$d" ]; then 
		echo "Making directory $2/$d"
		mkdir -p "$2/$d"
	fi
done
